package com.hotelBookingSystem.group.models;

import java.sql.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "register")


public class Booking {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String registerID;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private Date checkIN;
    @DynamoDBAttribute
    private Date checkOut;
    @DynamoDBAttribute
    private String city;
    @DynamoDBAttribute
    private String gender;
    @DynamoDBAttribute
    private String note;
    @DynamoDBAttribute
    private boolean physicalAssisstance;
    @DynamoDBAttribute
    private String roomView;
    @DynamoDBAttribute
    private String roomTypes;


    @Override
    public String toString() {

        return "Booking [userID=+ registerID + , name=" + name + ", email=" + email + ", checkIN=" + checkIN
                + ", checkOut=" + checkOut + ", city=" + city + ", gender=" + gender + ", note=" + note
                + ", physicalAssisstance=" + physicalAssisstance + ", roomView=" + roomView +  ", roomTypes=" + roomTypes + "]";
    }

   public String getUserID() {
        return registerID;
    }

    public void setUserID(String userID) {
        this.registerID = userID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getCheckIN() {
        return checkIN;
    }

    public void setCheckIN(Date checkIN) {
        this.checkIN = checkIN;
    }

    public Date getCheckOut() {
        return checkOut;
    }

    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public boolean isPhysicalAssisstance() {
        return physicalAssisstance;
    }

    public void setPhysicalAssisstance(boolean physicalAssisstance) {
        this.physicalAssisstance = physicalAssisstance;
    }

    public String getRoomView() {
        return roomView;
    }

    public void setRoomView(String roomView) {
        this.roomView = roomView;
    }

    public String getRoomTypes() {
        return roomTypes;
    }

    public void setRoomTypes(String roomTypes) {
        this.roomTypes = roomTypes;
    }






    //OLD
    /*@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String bookingId;
    @DynamoDBAttribute
    private String hotelName;
    @DynamoDBAttribute
    private String roomNumber;
    @DynamoDBAttribute
    private String checkIn;
    @DynamoDBAttribute
    private String checkOut;
    @DynamoDBAttribute
    private Invoice invoice;

     */

}