package com.hotelBookingSystem.group.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "booking")


public class Booking {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String bookingId;
    @DynamoDBAttribute
    private String hotelName;
    @DynamoDBAttribute
    private String roomNumber;
    @DynamoDBAttribute
    private String checkIn;
    @DynamoDBAttribute
    private String checkOut;
    @DynamoDBAttribute
    private Invoice invoice;

}