package com.hotelBookingSystem.group.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
@DynamoDBTable(tableName = "features")
public class Features {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String featuresId;
    @DynamoDBAttribute
    private boolean workDesk;
    @DynamoDBAttribute
    private String conciergeService;
    @DynamoDBAttribute
    private String seaView;
    @DynamoDBAttribute
    private String twentyFourSevenRoomService;
    @DynamoDBAttribute
    private String smartphoneForRoomControl;

}

